### ISSUE TITLE
Is the running failure? What did I do wrong?

### ISSUE THREAD

**Issue by Deja-vuuu** [flowtyone/flowty-realtime-lcm-canvas#2]
<img width="1016" alt="image" src="https://github.com/flowtyone/flowty-realtime-lcm-canvas/assets/27748682/29b6ba71-b35f-4496-9c8d-12cae0f1f91e">

**Comment by flowtyone** [comment]
Seems like a network issue, try again?

**Comment by douxc** [comment]
@flowtyone same issuse, i try download the model file(diffusion_pytroch_model.fp16.safetensors) and move to models folder, but it still try to download from network when i rerun `ui.py`. what should i do?

**Comment by flowtyone** [comment]
You shouldn't download them manually. Delete the models folder and just run the script, it will download everything automatically
